name: moss_tts_nano
description: MOSS-TTS-Nano - A cross-platform TTS application powered by Flutter and ONNX Runtime.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  audioplayers: ^6.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  http: ^1.2.1
  archive: ^3.4.10
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
